#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GendacCoreApp.Droid.Resource", IsApplication=true)]

namespace GendacCoreApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int planets_array = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int Header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btnBLE = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int btnCON = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int btnComms = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int btnMaps = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int btnNFC = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int btnVision = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BLE = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int comms = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CONF = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int homescreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int maps = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NFC = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int vision = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
